# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://coffeencoke.com
title: Coffeencoke
subtitle: Matt Simpson's blog
author: Matt Simpson
description: Blog for Coffeencoke - Matt Simpson - about Computer Science, Programming Languages, Community, and Entrepreneurship
keywords: Matt, Simpson, Matt Simpson, Coffeencoke, Computer Science, Programming Languages, Community, Entrepreneurship, Entrepreneur, Software Development, St. Louis, Ruby, Rails, Ruby on Rails
permalink: /blog/:year/:month/:day/:title/
pygments: true
markdown: redcarpet
safe: false
handle: coffeencoke

date_format: "ordinal"

paginate: 5
paginate_path: "blog/pages/:num"

tag_page_layout: tags
tag_page_dir: blog/tags
